### ISSUE TITLE
Routing Implementation

### ISSUE THREAD

**Issue by aozisik** [aozisik/Crust#1]
A practical implementation of rails-like routing is missing!

**Comment by netimaj** [comment]
Ne close mlose ediyon lenJ

 

Batunet.com icin email adresi kurma ve kullanmayi yapabilir misin (acil) J

 

---

Alper Kazakoğlu

Software-Entwicklung & Online-Marketing

Klosterstr. 40a, D-52531 Übach-Palenberg

 

E:  <mailto:info@netimaj.com> info@netimaj.com W:  <http://www.netimaj.com/> www.netimaj.com

TEL: +90.531.833.4242 SMS: +90.531.833.4242

 

Von: Ahmet Özışık [mailto:notifications@github.com] 
Gesendet: Dienstag, 27. Januar 2015 21:09
An: aozisik/Crust
Betreff: Re: [Crust] Routing Implementation (#1)

 

Closed #1 <https://github.com/aozisik/Crust/issues/1> .
